bump_version: null
lint: null
nf_core_version: 3.0.1
org_path: null
repository_type: pipeline
template:
  author: chase mateusiak <chasem@wustl.edu>
  description: An automated processing pipeline for mammalian bulk calling cards experiments
  force: false
  is_nfcore: true
  name: callingcards
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0.0
update: null
