nf_core_version: 3.2.1
repository_type: pipeline
template:
  author: chase mateusiak <chasem@wustl.edu>
  description: An automated processing pipeline for mammalian bulk calling cards experiments
  force: false
  is_nfcore: true
  name: callingcards
  org: nf-core
  outdir: .
  version: 1.0.0
